import Footer from "../components/Layout/Footer";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "../components/Layout/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   variable:"Outfit",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const outfit = Outfit({
//   variable: "--outfit",
//   variable:"Outfit",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Isecurion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
